ceph/dmclock

- sim/sim_client.h
Make granularity of client request interval be finer to test client iops goal more than 1000 IOPs.
> Make granularity of client request interval be finer

- sim/simulate.h
Fix uninitialized value of client's server selection in the client initialization process.
The below table shows each client & request's server selection result.
Current:
==== Server Selected ====
client:   0   1   2   3   4   5   6   7   8   9 .. 90  91  92  93  94  95  96  97  98  99
r_0:   **0   0   0   0   0   0   0   0   0   0 ..  0   0   0   0   0   0   0   0   0  99**  >> at this time, client_count is not initialized
r_1:   1   1   1   1   1   1   1   1   1   1  .. 91  92  93  94  95  96  97  98  99   0
r_2:   2   3   4   5   6   7   8   9  10  11 .. 92  93  94  95  96  97  98  99   0   1
After:
==== Server Selected ====
client:   0   1   2   3   4   5   6   7   8   9 .. 90  91  92  93  94  95  96  97  98  99
r_0:   **0   1   2   3   4   5   6   7   8   9 .. 90  91  92  93  94  95 …
> Fix server selection error

- dmc_sim.conf
- sim/CMakeLists.txt
- sim/ConfUtils.cc
- sim/ConfUtils.h
- sim/config.cc
- sim/config.h
- sim/str_list.cc
- sim/str_list.h
- sim/test_dmclock_main.cc
When executing dmc_sim, configuration filename will be received as parameter so that we could execute multiple tests easily.
For example, for new test with new parameters(like server count, client iops... etc) we just add new configuration file without recompiling.
Moreover we can replay the test just with the configuration file we want to test.
**- Usage**
**1. ./sim/dmc_sim -c/--conf ./dmc_sim.conf (dmclockparameter configuration file)**
**2. dmc_sim.conf(example)**
**[global]**
**server_count= 1**                              _// the total number of servers_
**client_count= 3**                                _// the total number of clients_
**server_types= 1**                              _// types of servers (Ex. server_count=100, server_types=3 >> server i(0~99)‘s type = i% …
> Add file based dmclock configuration parameter functionality

- sim/src/sim_client.h
- sim/src/simulate.h
- sim/src/test_dmclock_main.cc
I recently tested large numbers for config parameters for testing high performance device configuration. But, client_total_ops was uint16_t  type. Because it was too small, test didn't work properly.
In this PR, I changed some variables' type from uint16_t to uin32_t. And I fixed output format to print large number properly. Because large numbers with long digits were concatenated with each others without delimiter. It was hard to read the number. Therefore, I added single space between output numbers. But small numbers will be printed same as previous result output because I reduced 'data_w' by 1 for compensation about one added blank.
```
#Test Configuration
[global]
server_groups = 1
client_groups = 1
server_random_selection = false
server_soft_limit = false
[client.0]
client_count = 5 …
```
> Large client_total_ops

- src/dmclock_server.h
The selected client is not the top of all heaps. So, some heaps need
promotion not demotion. The effect of this change can be seen at the below configuration clearly.
```
[global]                       
server_groups = 1              
client_groups = 2              
server_random_selection = false
server_soft_limit = true       
[client.0]                     
client_count = 1               
client_wait = 0                
client_total_ops = 1000        
client_server_select_range = 4 
client_iops_goal = 60          
client_outstanding_ops = 100   
client_reservation = 20.0      
client_limit = 70.0            
client_weight = 1.0            
[client.1]                     
client_count = 1               
client_wait = 0                
client_total_ops = 8000 …
```
> Change limit heap to use adjust() instead of demote() after request pop.

- sim/src/simulate.h
Fix to print result of the last second.
```
==== Client Data ====
client:       0  total
t_0:  148.50  148.50
t_1:  148.50  148.50
t_2:  148.50  148.50
t_3:   54.50   54.50      <== This part was missed previously for all tests.
t_4:    0.00    0.00
res_ops:     334     334
prop_ops:     666     666
```
> Fix to print result of the last second

- src/dmclock_server.h
I found a case that break the right proportional shares. I analysed this and found that sometimes prop_delta was set 0 for the newly inserted client record. In this dmclock code, the idle flag is not apply current state and take some times. Therefore, even if client had no request the client was not marked as idle. When a new client was inserted it would have 0 for prop_delta if other active clients didn't have any request. Consequently, new client will got proportional I/O service based on wrong prop_delta.
To fix this, I use other clients' previous tag when the other client didn't have any request in its queue.
**Config file**
```
[global]
server_groups = 1
client_groups = 2
server_random_selection = false
server_soft_limit = false
[client.0]
client_count = 1
client_wait = 0 …
```
> Fix idle client's prop_delta to set with others' previous tag when its queue is empty

- test/CMakeLists.txt
- test/dmtest-config.h.in
- test/test_dmclock_server.cc
Fixes: http://tracker.ceph.com/issues/19979
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
> dmclock: Don't dump core when using EXPECT_DEATH_IF_SUPPORTED

- CMakeLists.txt
- src/CMakeLists.txt
Set compiler flags at higher level CMakeLists.txt file, so they apply
to sim and test, and so earlier versions of GCC know to use c++11
standard. Clean up cmake files in general.
> Fix cmake files to handle GCC version 4 and other clean-up.

- sim/src/sim_client.h
- sim/src/sim_server.h
- sim/src/ssched/ssched_server.h
- sim/src/test_dmclock_main.cc
- sim/src/test_ssched_main.cc
- src/dmclock_server.h
- test/test_dmclock_server.cc
this requires the request type support move semantics, but the upside is
that the request type will not be copied under any circumstances.
Signed-off-by: Kefu Chai <kchai@redhat.com>
> enforce move semantics of request types

- CMakeLists.txt
- cmake/modules/BuildGTest.cmake
- src/dmclock_client.h
- src/dmclock_server.h
- test/CMakeLists.txt
debian stopped shipping googletest binaries, but it offers googletest in
the source form. so we can use it instead.
Signed-off-by: Kefu Chai <kchai@redhat.com>
> cmake: build gtest if not found

- src/dmclock_server.h
Signed-off-by: dingdangzhang <boqian.zy@alibaba-inc.com>
since there is such a return why break statement?so delete it.
> dmclock_server.h: remove redundant break statement

- src/dmclock_util.h
Signed-off-by: Yan Jun <yan.jun8@zte.com.cn>
> use clock_gettime() instead of gettimeofday() function

- CMakeLists.txt
- src/CMakeLists.txt
- src/dmclock_server.h
Moved the check for cmake's DO_NOT_DELAY_TAG_CALC to the top level, so it will affect how tests are built. Also addressed an unused variable when DO_NOT_DELAY_TAG_CALC is not defined.
> Fix issues regarding building and DO_NOT_DELAY_TAG_CALC

- sim/src/sim_recs.h
- sim/src/ssched/ssched_server.h
- support/src/run_every.h
With upgrade to gcc 7.1.1, need to include <functional> in additional header files.
> cleanup: fix includes for gcc 7.1.1

- src/dmclock_server.h
The following warning appears during build using gcc (GCC) 7.1.1.
```
ceph/src/dmclock/src/dmclock_server.h:948:11: warning: ‘*((void*)& result +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
return result;
^~~~~~
ceph/src/dmclock/src/dmclock_server.h:1024:11: warning: ‘*((void*)& result +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
return result;
^~~~~~
```
Signed-off-by: Jos Collin <jcollin@redhat.com>
> src/dmclock_server.h: silence warning from -Wmaybe-uninitialized

- sim/src/config.cc
- sim/src/config.h
- sim/src/test_dmclock_main.cc
- src/dmclock_server.h
The deceptive idleness problem is addressed in the below paper.
https://www.usenix.org/system/files/conference/atc13/atc13-shen.pdf
The dmClock has the same problem because it is also one of fair queueing type schedulers.
I applied anticipation_timeout variable for the tag calculation to solve the deceptive idleness problem.
A request that is arrived in short time after previous request's arrival will not be set current time as its tag, even if the calculated tag value is greater than the current time.
This change helps a client to take their unused resource that could be forfeited by other aggressive clients.
Specifically, in random mode, the resource forfeiture is worse because the request arrival time is irregular, tag value is frequently set to the current time during tag calculation. …
>  Add anticipation duration that keeps from resetting tag values to the current time

- src/dmclock_server.h
The coverity scan published in ceph-devel on 2017-09-21 revealed some uninitialized data in a constructor. This fixes that.
> Fix uninitialized scalar data

- sim/src/test_dmclock.h
- sim/src/test_dmclock_main.cc
- src/dmclock_client.h
- test/test_dmclock_client.cc
Allow the calculations of rho and delta to be handled by a "tracker"
specified via template parameter (i.e., by static polymorphism). The
tracker follows a simple interface constisting of three functions and
one static function.
Add a BorrowingTracker. Make it the default tracker. Add unit tests
for it. Maintain the original calculations as the OrigTracker.
> Made delta/rho calculations more flexible via tracker plug-in; make default a borrowing tracker

- src/dmclock_server.h
Change initialization of IndIntruHeapData to C++'s value-initialization to better future-proof the code.
> Change ClientRec's initalization of indirect intrusive heap data

- sim/src/test_dmclock_main.cc
- src/dmclock_server.h
- test/test_dmclock_server.cc
to avoid unnecessary memcpy. in the use case of Ceph, ClientInfo is
actually static constants. and is not a small struct per se: 6 double
member variables. we create a client info and copy it, for every single
request. it could be optimized off by using a pointer.
Signed-off-by: Kefu Chai <kchai@redhat.com>
> ClientRec: instead of a copy of ClientInfo, keep a pointer to it

- src/dmclock_server.h
I missed adding anticipation_timeout argument for a constructor at the previous PR.
If this PR is merged I will make a ceph PR that makes anticipation timeout be configurable for ceph.
The code will be https://github.com/TaewoongKim/ceph/commit/8f17269f534dfbf7acebd7fd5ad251df4592b2c8
> Add missing anticipation_timeout argument to PullPriorityQueue constructor

- sim/src/CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
It is not really our business to debug boost, gtest or our other
dependencies. Mark them as system includes.
> build: Mark dependency includes as SYSTEM in dmclock

- src/dmclock_recs.h
I think it's too large using default enum class type for the PhaseType.
Rather than using 4 bytes, It would be better to use only 1 byte.
Furthermore, the current ceph's denc.h implementation doesn't support 4 or 2 bytes underlying typed enum. (I don't know it's intended or not).
Anyway, I think decreasing the size would be good.
> Reduce the size of enum class PhaseType

- src/dmclock_server.h
- test/test_dmclock_server.cc
if a caller allocates their own R and passes it as a RequestRef into
PullPriorityQueue::add_request(), they should get that same pointer back
from the callbacks used by PriorityQueueBase::remove_by_*()
this is important if the request was instead allocated as some type
derived from R - in that case, the callback with R&& only gives back
part of the original object
> PriorityQueueBase uses RequestRef&& for remove_by callbacks

- sim/src/ConfUtils.cc
- sim/src/ConfUtils.h
- sim/src/simulate.h
- sim/src/str_list.h
- support/src/run_every.h
This pull request adds a small enhancement by avoiding copying data when unnecessary and mitigates the following cppcheck messages:
```
[sim/src/ConfUtils.cc:41]: (performance) Function parameter 'val_' should be passed by reference.
[sim/src/ConfUtils.cc:42]: (performance) Function parameter 'newsection_' should be passed by reference.
[sim/src/ConfUtils.cc:42]: (performance) Function parameter 'comment_' should be passed by reference.
[sim/src/ConfUtils.h:40]: (performance) Function parameter 'val_' should be passed by reference.
[sim/src/ConfUtils.h:41]: (performance) Function parameter 'newsection_' should be passed by reference.
[sim/src/ConfUtils.h:41]: (performance) Function parameter 'comment_' should be passed by reference.
[sim/src/str_list.h:96]: (performance) Function …
```
>  Added const references to various function parameters

- sim/src/sim_server.h
Rename the parameter "delay" to "finishing_check_period" in sim_server.h.
> Change variable name delay to finishing_check_period for clarity

- sim/src/sim_recs.h
- support/test/test_ind_intru_heap.cc
- support/test/test_indirect_intrusive_heap.cc
- support/test/test_intrusive_heap.cc
Set 4 constructors as explicit to avoid implicit usage.
Fix for cppcheck warning:
Class has a constructor with 1 argument that is
not explicit. Such constructors should in general be explicit for
type safety reasons. Using the explicit keyword in the constructor
means some mistakes when using the class can be avoided.
For more information check:
https://www.codeproject.com/Articles/28663/Explicit-Constructor-in-C
Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>
> misc: mark constructors as explicit

- .gitignore
- sim/dmc_sim_example.conf
- sim/src/config.cc
- sim/src/config.h
- sim/src/sim_client.h
- sim/src/sim_recs.h
- sim/src/sim_server.h
- sim/src/ssched/ssched_client.h
- sim/src/ssched/ssched_server.h
- sim/src/test_dmclock.cc
- sim/src/test_dmclock.h
- sim/src/test_dmclock_main.cc
- sim/src/test_ssched_main.cc
- src/dmclock_client.h
- src/dmclock_recs.h
- src/dmclock_server.h
- test/test_dmclock_client.cc
- test/test_dmclock_server.cc
- test/test_test_client.cc
Allow the dmclock library to handle the "cost" of an operation/request. This is in contrast to just measuring ops. If the cost is set at the value 1, then it's equivalent to the old code.
The cost is calculated on the server side and affects the tag values for the request. Furthermore, the cost is then sent back to the client, so the ServiceTracker can use the cost to properly calculate delta and rho values.
We now allow the delta and rho values sent with a request to be zero, since the request cost is included on the server-side tag calculation, and the request cost must be positive guaranteeing the advancement of tags.
The OrigTracker has now been updated so as not to add one when computing delta and rho.
The unit tests have been updated to use request costs. And the simulator has been …
> Allow the dmclock library to handle the "cost" of an operation/request

- CMakeLists.txt
- README.md
- src/dmclock_server.h
- test/test_dmclock_server.cc
part of ongoing work in https://github.com/ceph/dmclock/pull/50, where `AtLimit::Reject` is not compatible with delayed tag calculation. posting separately for review
provides two overloads of functions `initial_request_tag()`, `update_next_tag()`, and `reduce_reservation_tags()`, and uses [tag dispatch](https://www.boost.org/community/generic_programming.html#tag_dispatching) to select the desired overload
> server: delayed tag calculation as a template parameter

- src/dmclock_server.h
- test/test_dmclock_server.cc
replaces `bool allow_limit_break` with an `enum AtLimit` to enable a third option, whereby calls to `add_request()` will fail with `EAGAIN` if the client is at/above its limit
add a tunable threshold for `AtLimit::Reject` such that requests are only rejected once the limit is over this threshold. this is intended to help balance the queue depth with the desire to enforce an upper bound on the time spent waiting in the queue (and the memory use associated with queued requests)
for example, setting this threshold to 1 second for a client with limit=10 would allow that client to enqueue 10 requests before any are rejected. with a threshold of 0, all but the first would be rejected and require the client to resubmit
to simplify queue construction, a variant type `AtLimitParam` allows …
> add option to reject requests to clients over limit

- sim/src/test_dmclock_main.cc
server_soft_limit from test configuration file is bool type, it should change as the AtLimit has been introduced. Otherwise the sim test can't work.
Signed-off-by: yanjun <yan.jun8@zte.com.cn>
> sim: fix server_soft_limit can't work properly

- src/dmclock_server.h
- test/test_dmclock_server.cc
take the following configuration into account, we found something interesting:
```
[global]
server_groups = 1
client_groups = 1
server_random_selection = 1
server_soft_limit = 0
anticipation_timeout = 0.000
[client.0]
client_count = 1
client_wait = 0
client_total_ops = 10000          // for longer test
client_server_select_range = 10
client_iops_goal = 2000
client_outstanding_ops = 500      // make request queued
client_reservation = 50.0         // with reservation 
client_limit = 100.0
client_weight = 10.0
client_req_cost = 1
[server.0]
server_count = 10
server_iops = 50
server_threads = 1
```
1) At **ImmediateTagCalc** mode,  if we set no small reservation and large outstanding ops for a client to make request queued long in server, we got the IOPS leap high and then fall down …
> server: fix wrong calculation to reduce reservation tags

- CMakeLists.txt
- test/CMakeLists.txt
so the super-project can included dmclock's root directory. as the
"dmclock" target's target_include_directory() uses "$PROJECT_SOURCE_DIR"
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> cmake: tell if we are included as subproject or not

- src/dmclock_server.h
- support/src/run_every.cc
- support/src/run_every.h
- test/test_dmclock_server.cc
If there are a large number of clients become old enough to erase in a short time, request may be blocked for a long time. since `do_clean` hold the `data_mtx` lock, other functions `pull_request` or `empty`  have to  wait.
Actually, in one of our testcase of ceph, it switch the `osd_op_queue` to `mclock_client`,  then we create 75, 000 rbd images in a short time, which brings huge clients. it result in OSD be marked down.
```
2018-12-20 20:16:17.266463 7f8bf21b8700  1 heartbeat_map is_healthy 'OSD::osd_op_tp thread 0x7f8bc310c700' had timed out after 60
2018-12-20 20:16:17.691459 7f8bcd921700  0 log_channel(cluster) log [WRN] : Monitor daemon marked osd.15 down, but it is still running
2018-12-20 20:16:17.691491 7f8bcd921700  0 log_channel(cluster) log [DBG] : map e638 wrongly marked me …
```
> server: fix request blocked caused by do_clean

- src/dmclock_server.h
the compiler is able to figure it out. also this change fixes the FTBFS
with GCC-9.
* do not specify the template argument for get_or_default()
* cast the RejectThreshold parameter to `RejectThreshold`, as 0 is an
integer, while we are using `double` to represent `Time` here.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> dmclock_server: do not specify template argument for get_or_default()

- src/dmclock_server.h
- support/src/indirect_intrusive_heap.h
As we discussed in https://github.com/ceph/dmclock/pull/67, **do_clean** might take minutes to erase the old clients if there are thousands of clients became old enough to erase, which result in some unanticipated situation such as request been blocked. so I pushed that PR(https://github.com/ceph/dmclock/pull/67) to limit number of old clients to be erased at a time, it can largely ameliorate this problem. However, it doesn't look perfect since it didn't reduce the time to erase one old client.
Recently , I dig into the code further more and find the time is mainly consumed by **delete_from_heaps** at [#L258](https://github.com/ceph/dmclock/blob/master/support/src/indirect_intrusive_heap.h#L258), and finally [#L223](https://github.com/ceph/dmclock/blob/master/support/src/indirect_intrusive …
> server,heap: severely enhance performance for delete_from_heaps

- sim/src/config.cc
- sim/src/config.h
- sim/src/sim_recs.h
- sim/src/simulate.h
- sim/src/test_dmclock_main.cc
- sim/src/test_ssched_main.cc
- src/dmclock_server.h
- src/dmclock_util.cc
- src/dmclock_util.h
- support/test/test_indirect_intrusive_heap.cc
- test/test_dmclock_server.cc
`uint` and friends are only for backward compatibility. they are not
standardized. and is only available in glibc when `_GNU_SOURCE` is defined.
other implementations of libc might or might not define this type.
we should avoid using it. `unsigned` is used to replace `uint`. and
as an alternative, `size_t` is used when `uint` is used as an index of
array, as `std::size_t` is the index's type used by
`std::vector::operator[]`.
see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59945
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> sim.src,support,test: replace uint with unsigned/size_t

- support/src/indirect_intrusive_heap.h
uint is undefined on musl as it isnt a standard type.
Replaced uint with the standard type "unsigned int" to resolve compilation issue on musl.
> Make K use a standard type

- src/dmclock_server.h
by holding the lock while signaling, we avoid missing that signal in run_sched_ahead() and hanging forever at:
```c++
if (TimeZero == sched_ahead_when) {
sched_ahead_cv.wait(l);
```
Fixes: https://tracker.ceph.com/issues/46734
> ~PushPriorityQueue signals sched_ahead_cv under lock

- src/dmclock_server.h
Adds a predicate to some calls to wait, so waits can leave early when shutting down.
Cleans up the code in a few areas.
> cleanups for run_sched_ahead()

- src/dmclock_util.cc
MinGW complains:
```
/home/ubuntu/dmclock/src/dmclock_util.cc: In function ‘void crimson::dmclock::debugger()’:
/home/ubuntu/dmclock/src/dmclock_util.cc:33:9: error: ‘SIGCONT’ was not declared in this scope
raise(SIGCONT);
^~~~~~~
/home/ubuntu/dmclock/src/dmclock_util.cc:33:9: note: suggested alternative: ‘SIGINT’
raise(SIGCONT);
^~~~~~~
SIGINT
```
SIGCONT is not defined on Windows.
Replace the call with `DebugBreak`.
Signed-off-by: Alin Gabriel Serdean <aserdean@cloudbasesolutions.com>
> util: Fix MinGW compilation error

- src/dmclock_server.h
I have read the [PR58](https://github.com/ceph/dmclock/pull/58) and think there still exist some problems in reduce_reservation_tags function especially when cost is not 1.
take the following configuration.
```
[global]
server_groups = 1
client_groups = 2
server_random_selection = 1
server_soft_limit = 0
anticipation_timeout = 0.000
[client.0]
client_count = 1
client_wait = 0
client_total_ops = 5000       
client_server_select_range = 10
client_iops_goal = 5000
client_outstanding_ops = 10000      // make request queued
client_reservation = 100.0      // with reservation 
client_limit = 100000000.0
client_weight = 100.0
client_req_cost = 5
[client.1]
client_count = 2
client_wait = 4      // make client.0 handled in weight-based phase in the first 4 seconds     
client_total_ops = 40000 …
```
> server: fix reduce_reservation_tags function with cost

- src/dmclock_server.h
- test/test_dmclock_server.cc
The first issue is that the run_sched_ahead() function is blocked when the push priority queue is employed. It is confirmed that the sched_ahead_cv.wait() isn't signaled if the predicate function returns false with this->finishing variable.  For this reason, sched_ahead_when > TimeZero condition is added pred() function. 
The other is that the further request is not fetched when the schedule_request() executes the submit_request() and  sched_ahead_when is set to TimeZero. It implies that run_sched_ahead thread can't wake up by itself. This commit adds that the schedule_request() is called while requests are ready and sched_ahead_when is equal to TimeZero. A unit test has also been added to check whether 3 requests are dispatched after a few seconds.
Fixes: …
> server: fix run_sched_ahead() scheduling issue
